"""
Newspaper Generator - Creates daily newspaper in JSON, HTML, and PDF formats
"""

import os
import json
from typing import Dict, Any, List
from pathlib import Path
from datetime import datetime
import logging


class NewspaperGenerator:
    """Generates daily newspaper in multiple formats"""
    
    HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - {date}</title>
    <style>
        body {{
            font-family: 'Georgia', serif;
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
            color: #333;
        }}
        .newspaper {{
            background-color: white;
            padding: 40px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }}
        .header {{
            text-align: center;
            border-bottom: 3px solid #333;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }}
        .header h1 {{
            font-size: 48px;
            margin: 0;
            font-weight: bold;
            letter-spacing: 2px;
        }}
        .header .subtitle {{
            font-size: 14px;
            color: #666;
            margin-top: 10px;
        }}
        .date {{
            font-style: italic;
            color: #666;
            margin: 10px 0;
        }}
        .editorial {{
            font-style: italic;
            background-color: #f9f9f9;
            padding: 20px;
            margin: 20px 0;
            border-left: 4px solid #333;
        }}
        .section {{
            margin: 40px 0;
        }}
        .section-title {{
            font-size: 32px;
            font-weight: bold;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }}
        .article {{
            margin: 30px 0;
            padding: 20px 0;
            border-bottom: 1px solid #ddd;
        }}
        .article:last-child {{
            border-bottom: none;
        }}
        .article-headline {{
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 10px;
            color: #000;
        }}
        .article-meta {{
            font-size: 12px;
            color: #666;
            margin-bottom: 15px;
        }}
        .article-tldr {{
            font-style: italic;
            margin: 15px 0;
            color: #555;
        }}
        .article-bullets {{
            margin: 15px 0;
        }}
        .article-bullets li {{
            margin: 8px 0;
        }}
        .article-significance {{
            background-color: #f0f8ff;
            padding: 15px;
            margin: 15px 0;
            border-left: 3px solid #0066cc;
        }}
        .article-links {{
            margin-top: 15px;
            font-size: 12px;
        }}
        .article-links a {{
            color: #0066cc;
            text-decoration: none;
            margin-right: 15px;
        }}
        .article-links a:hover {{
            text-decoration: underline;
        }}
        .toc {{
            background-color: #f9f9f9;
            padding: 20px;
            margin: 20px 0;
            border: 1px solid #ddd;
        }}
        .toc h2 {{
            margin-top: 0;
        }}
        .toc ul {{
            list-style: none;
            padding-left: 0;
        }}
        .toc li {{
            margin: 8px 0;
        }}
        .footer {{
            margin-top: 50px;
            padding-top: 20px;
            border-top: 2px solid #333;
            text-align: center;
            font-size: 12px;
            color: #666;
        }}
        .metadata {{
            background-color: #f9f9f9;
            padding: 15px;
            margin: 20px 0;
            font-size: 12px;
            color: #666;
        }}
    </style>
</head>
<body>
    <div class="newspaper">
        <div class="header">
            <h1>{title}</h1>
            <div class="subtitle">Daily Research & News Bulletin</div>
            <div class="date">{date}</div>
        </div>
        
        {editorial}
        
        {toc}
        
        {sections}
        
        <div class="metadata">
            <strong>Generation Details:</strong><br>
            Generated: {generated_at}<br>
            Sources: {sources_count} | Research Papers: {papers_count} | News Articles: {news_count}
        </div>
        
        <div class="footer">
            <p>This newspaper was automatically generated by the MCP Research Bot.</p>
            <p>All content is sourced from publicly available research papers and news articles.</p>
            <p>© {year} - For research and educational purposes only.</p>
        </div>
    </div>
</body>
</html>
"""
    
    def __init__(self, config: Dict[str, Any], logger: logging.Logger):
        """
        Initialize newspaper generator
        
        Args:
            config: Configuration dictionary
            logger: Logger instance
        """
        self.config = config
        self.logger = logger
        
        # Create output directories
        self.base_dir = Path(config.get('storage', {}).get('newspapers_dir', './data/newspapers'))
        self.base_dir.mkdir(parents=True, exist_ok=True)
    
    def generate(self, items: List[Dict[str, Any]], topics: List[str], date: str) -> Dict[str, Any]:
        """
        Generate newspaper in all formats
        
        Args:
            items: List of items with summaries and scores
            topics: List of topics
            date: Date string (YYYY-MM-DD)
            
        Returns:
            Dictionary with newspaper data and file paths
        """
        self.logger.info(f"Generating newspaper for {date}...")
        
        # Create date-specific directory
        date_dir = self.base_dir / date
        date_dir.mkdir(parents=True, exist_ok=True)
        
        # Organize items into sections
        sections = self._organize_sections(items)
        
        # Generate editorial
        editorial = self._generate_editorial(items, topics)
        
        # Create newspaper structure
        newspaper_data = {
            'date': date,
            'title': f"Daily Research Bulletin: {', '.join(topics[:2])}",
            'topics': topics,
            'editorial': editorial,
            'sections': sections,
            'metadata': {
                'generated_at': datetime.now().isoformat(),
                'sources_count': len(set(item.get('source', '') for item in items)),
                'papers_count': len([i for i in items if i.get('type') == 'research']),
                'news_count': len([i for i in items if i.get('type') == 'news']),
                'total_items': len(items)
            }
        }
        
        # Generate outputs
        paths = {}
        
        # 1. JSON
        json_path = date_dir / 'newspaper.json'
        with open(json_path, 'w', encoding='utf-8') as f:
            json.dump(newspaper_data, f, indent=2, ensure_ascii=False)
        paths['json'] = str(json_path)
        self.logger.info(f"Generated JSON: {json_path}")
        
        # 2. HTML
        html_path = date_dir / 'newspaper.html'
        html_content = self._generate_html(newspaper_data)
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        paths['html'] = str(html_path)
        self.logger.info(f"Generated HTML: {html_path}")
        
        # 3. PDF (if enabled)
        if 'pdf' in self.config.get('output', {}).get('formats', []):
            try:
                pdf_path = self._generate_pdf(html_path, date_dir)
                if pdf_path:
                    paths['pdf'] = str(pdf_path)
                    self.logger.info(f"Generated PDF: {pdf_path}")
            except Exception as e:
                self.logger.error(f"PDF generation failed: {str(e)}")
        
        return {
            'data': newspaper_data,
            'paths': paths
        }
    
    def _organize_sections(self, items: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Organize items into sections"""
        from src.ai.headline_generator import HeadlineGenerator
        
        # Use headline generator to assign sections
        headline_gen = HeadlineGenerator(self.config, self.logger)
        sections_dict = headline_gen.assign_sections(items)
        
        # Convert to list format
        sections = []
        section_config = {
            'top_research': 'Top Research Picks',
            'rapid_news': 'Rapid News',
            'methods_tools': 'Methods & Tools',
            'short_briefs': 'Short Briefs',
            'full_summaries': 'Full Summaries'
        }
        
        for section_id, section_title in section_config.items():
            if section_id in sections_dict and sections_dict[section_id]:
                sections.append({
                    'id': section_id,
                    'title': section_title,
                    'items': sections_dict[section_id]
                })
        
        return sections
    
    def _generate_editorial(self, items: List[Dict[str, Any]], topics: List[str]) -> str:
        """Generate editorial lead"""
        if not items:
            return "No items to report today."
        
        top_items = items[:3]
        
        editorial = f"Today's highlights in {', '.join(topics)}: "
        
        highlights = []
        for item in top_items:
            title = item.get('headline', item.get('title', ''))[:80]
            source = item.get('source', 'Unknown')
            highlights.append(f"{title} ({source})")
        
        editorial += '; '.join(highlights) + '.'
        
        return editorial
    
    def _generate_html(self, newspaper_data: Dict[str, Any]) -> str:
        """Generate HTML from newspaper data"""
        # Generate table of contents
        toc_html = '<div class="toc"><h2>Contents</h2><ul>'
        for section in newspaper_data['sections']:
            toc_html += f'<li><a href="#{section["id"]}">{section["title"]} ({len(section["items"])})</a></li>'
        toc_html += '</ul></div>'
        
        # Generate editorial
        editorial_html = f'<div class="editorial">{newspaper_data["editorial"]}</div>'
        
        # Generate sections
        sections_html = ''
        for section in newspaper_data['sections']:
            sections_html += f'<div class="section" id="{section["id"]}">'
            sections_html += f'<h2 class="section-title">{section["title"]}</h2>'
            
            for item in section['items']:
                sections_html += self._generate_article_html(item)
            
            sections_html += '</div>'
        
        # Fill template
        html = self.HTML_TEMPLATE.format(
            title=newspaper_data['title'],
            date=newspaper_data['date'],
            editorial=editorial_html,
            toc=toc_html,
            sections=sections_html,
            generated_at=newspaper_data['metadata']['generated_at'],
            sources_count=newspaper_data['metadata']['sources_count'],
            papers_count=newspaper_data['metadata']['papers_count'],
            news_count=newspaper_data['metadata']['news_count'],
            year=datetime.now().year
        )
        
        return html
    
    def _generate_article_html(self, item: Dict[str, Any]) -> str:
        """Generate HTML for a single article"""
        html = '<div class="article">'
        
        # Headline
        headline = item.get('headline', item.get('title', 'Untitled'))
        html += f'<h3 class="article-headline">{headline}</h3>'
        
        # Metadata
        authors = ', '.join(item.get('authors', [])[:3])
        if len(item.get('authors', [])) > 3:
            authors += ' et al.'
        source = item.get('source', 'Unknown')
        date = item.get('published_at', '')[:10]
        
        html += f'<div class="article-meta">'
        if authors:
            html += f'{authors} | '
        html += f'{source}'
        if date:
            html += f' | {date}'
        html += '</div>'
        
        # TL;DR
        if item.get('tldr'):
            html += f'<div class="article-tldr">{item["tldr"]}</div>'
        
        # Bullets
        if item.get('bullets'):
            html += '<ul class="article-bullets">'
            for bullet in item['bullets']:
                html += f'<li>{bullet}</li>'
            html += '</ul>'
        
        # Significance
        if item.get('significance'):
            html += f'<div class="article-significance">'
            html += f'<strong>Why it matters:</strong> {item["significance"]}'
            html += '</div>'
        
        # Links
        html += '<div class="article-links">'
        if item.get('url'):
            html += f'<a href="{item["url"]}" target="_blank">📄 View Original</a>'
        if item.get('pdf_url'):
            html += f'<a href="{item["pdf_url"]}" target="_blank">📑 PDF</a>'
        if item.get('doi'):
            html += f'<a href="https://doi.org/{item["doi"]}" target="_blank">🔗 DOI</a>'
        html += '</div>'
        
        html += '</div>'
        
        return html
    
    def _generate_pdf(self, html_path: Path, output_dir: Path) -> Path:
        """Generate PDF from HTML"""
        pdf_path = output_dir / 'newspaper.pdf'
        
        pdf_engine = self.config.get('output', {}).get('pdf_engine', 'wkhtmltopdf')
        
        if pdf_engine == 'wkhtmltopdf':
            import pdfkit
            pdfkit.from_file(str(html_path), str(pdf_path))
        elif pdf_engine == 'weasyprint':
            from weasyprint import HTML
            HTML(filename=str(html_path)).write_pdf(str(pdf_path))
        else:
            self.logger.warning(f"Unknown PDF engine: {pdf_engine}")
            return None
        
        return pdf_path
